PersonalPortfolio/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using PersonalPortfolio.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace PersonalPortfolio.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public BlogController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            return View(_db.BlogPosts.Where(x => x.User.Id == currentUser.Id));
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(BlogPost blogpost)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            blogpost.User = currentUser;
            _db.BlogPosts.Add(blogpost);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var thisBlogPost = _db.BlogPosts
                                  .Include(x => x.Comments)
                                  .FirstOrDefault(items => items.BlogPostId == id);
            return View(thisBlogPost);
        }

        public IActionResult Edit(int id)
        {
            var thisBlogPost = _db.BlogPosts.FirstOrDefault(names => names.BlogPostId == id);
            return View(thisBlogPost);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BlogPost blogpost)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            blogpost.User = currentUser;
            _db.BlogPosts.Update(blogpost);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var thisBlogPost = _db.BlogPosts.FirstOrDefault(names => names.BlogPostId == id);
            return View(thisBlogPost);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisBlogPost = _db.BlogPosts.FirstOrDefault(names => names.BlogPostId == id);
            _db.Remove(thisBlogPost);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PersonalPortfolio/Controllers/ResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PersonalPortfolio.Controllers
{
    public class ResumeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

PersonalPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="css/styles.css">
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Account" asp-action="Index" class="navbar-brand" href="/Home">Patrick Napper Portfolio</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                    
                    <li><a asp-area="" asp-controller="Home" asp-action="About" href="/Home/About">About</a></li>
                    <li><a asp-area="" asp-controller="Blog" asp-action="Index" href="/Blog">Blog</a></li>
                    <li><a asp-area="" asp-controller="Resume" asp-action="Index" href="/Resume">Resume</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Project" href="/Home/Project">Projects</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact" href="/Home/Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Login" href="/Account/Login">Admin Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 Patrick Napper</p>
        </footer>
    </div> 
</body>
</html>